# Generated by Django 4.2.3 on 2023-09-07 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siswa', '0001_initial'),
        ('utama', '0002_alter_kelas_name_alter_semester_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dari_semester_sebelumnya', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('lunas', 'Lunas')], default='Aktif', max_length=100)),
                ('murid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.siswa')),
                ('smester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utama.semester')),
                ('tahun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utama.tahunpelajaran')),
                ('untuk_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utama.kelas')),
            ],
            options={
                'ordering': ['murid', 'smester'],
            },
        ),
        migrations.CreateModel(
            name='TandaTerima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_dibayar', models.IntegerField()),
                ('tanggal_bayar', models.DateField()),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
                ('tagihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keuangan.tagihan')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.CharField(max_length=100)),
                ('jumlah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utama.biayapendaftaran')),
                ('tagihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keuangan.tagihan')),
            ],
        ),
    ]
