# Generated by Django 4.2.3 on 2023-09-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagihan',
            name='status',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('lunas', 'Lunas')], default='aktif', max_length=20),
        ),
        migrations.AlterField(
            model_name='tandaterima',
            name='keterangan',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
