# Generated by Django 4.2.3 on 2023-09-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(choices=[('genap', 'Genap'), ('ganjil', 'Ganjil')], max_length=10),
        ),
    ]
