# Generated by Django 4.2.3 on 2023-09-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0002_alter_kelas_name_alter_semester_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(choices=[('ganjil', 'Ganjil'), ('genap', 'Genap')], max_length=10),
        ),
    ]
