# Generated by Django 4.2.3 on 2023-09-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0005_alter_semester_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
