# Generated by Django 4.2.3 on 2023-09-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0010_alter_semester_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(choices=[('genap', 'Genap'), ('ganjil', 'Ganjil')], max_length=10),
        ),
    ]
