# Generated by Django 4.2.3 on 2023-09-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='status',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('lulus', 'Lulus'), ('do', 'Drop Out')], default='Aktif', max_length=20),
        ),
    ]
