# Generated by Django 4.2.3 on 2023-09-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0005_alter_siswa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='gender',
            field=models.CharField(choices=[('wanita', 'Wanita'), ('pria', 'Pria')], max_length=30),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='status',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('do', 'Drop Out'), ('lulus', 'Lulus')], default='Aktif', max_length=20),
        ),
    ]
