# Generated by Django 4.2.3 on 2023-09-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0006_alter_siswa_gender_alter_siswa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='status',
            field=models.CharField(choices=[('do', 'Drop Out'), ('aktif', 'Aktif'), ('lulus', 'Lulus')], default='Aktif', max_length=20),
        ),
    ]
