# Generated by Django 4.2.3 on 2023-09-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0009_alter_siswa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='gender',
            field=models.CharField(choices=[('pria', 'Pria'), ('wanita', 'Wanita')], max_length=30),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='status',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('lulus', 'Lulus'), ('do', 'Drop Out')], default='Aktif', max_length=20),
        ),
    ]
